version: '3'

services:
  load-balance:
    build: ./load-balancer
    container_name: load-balance
    restart: always
    ports:
      - 3000:80
    depends_on:
      - react1
      - react2
      
  react1:
    build: .
    container_name: react1
    restart: always
    ports:
      - 3001:80
  react2:
    build: .
    container_name: react2
    restart: always
    ports:
      - 3002:80